kind: Deployment
metadata:
  labels:
    app: ${project.artifactId}
  name: ${project.artifactId}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      containers:
        - image: docker-registry.default.svc:5000/build/spring-cloud-gateway:latest
          imagePullPolicy: Always
          name: ${project.artifactId}
          resources:
            requests:
              memory: 256M
              cpu: 2000m
            limits:
              memory: 512M
              cpu: 4000m
          livenessProbe:
            httpGet:
              port: 8080
#              path: /alive
              path: /actuator/info
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 1
            httpGet:
              port: 8080
              path: /actuator/health





#metadata:
#  labels:
#    project: ${project.artifactId}
#    hystrix.enabled: true
#    hystrix.cluster: default
#    version: ${project.version}
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        project: ${project.artifactId}
#        hystrix.enabled: true
#        hystrix.cluster: default
#        version: ${project.version}
#    spec:
#      containers:
#        - resources:
#            limits:
#              memory: ${limits_memory}
#            requests:
#              memory: ${requests_memory}

#
#spec:
#  replicas: 1
#  template:
#    spec:
#      containers:
#        - resources:
#            limits:
#              memory: ${container.memory.limit}
#        - env:
#            - name: "GC_MAX_METASPACE_SIZE"
#              value: ${container.gc_max_metaspace_size}




#spec:
#  template:
#    spec:
#      containers:
#        - env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: mysql
#            - name: SPRING_DATASOURCE_USER
#              valueFrom:
#                secretKeyRef:
#                  name: baeldung-db
#                  key: database-user
#            - name: SPRING_DATASOURCE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: baeldung-db
#                  key: database-password
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 180
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 30
