spring:
  cloud:
    gateway:
      # avoid sending forwarded/x-forwarded headers from api-gateway, as they overwrite forwarded headers from nevis or loadbalancer
      forwarded:
        enabled: false
      x-forwarded:
        enabled: true
        prefix-enabled: true # this header modifies the uri of the request within the called service
        prefix-append: false
        proto-enabled: false
        proto-append: false
        port-enabled: false
        port-append: false
        host-enabled: false
        host-append: false
        for-enabled: false

      #      routes:
#        - id: service_route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/customer/**
#            - After=2019-12-08T20:27:00.001+01:00[Europe/Zurich]
#          filters:
#            - RewritePath=foo(?<segment>/?.*), $\{segment}
#        - id: foo-service_route
#          uri: http://foo-service
#          predicates:
#            - Path=/foo/**
#          filters:
#            - RewritePath=customer(?<segment>/?.*), $\{segment}
#        - id: openshift_route
#          predicates:
#            - Path=/myhelsana/services/medicheck/**
#            - Between=2019-12-08T20:28:00.001+01:00[Europe/Zurich], 2019-12-08T20:30:00.001+01:00[Europe/Zurich]
#          filters:
#            - StripPrefix=3
#            - RewritePath=/service(?<segment>/?.*), $\{segment}
#            - name: Logging
#              args:
#                baseMessage: My Custom Message
#                preLogger: true
#                postLogger: true
#          uri: "http://medicheck-service-development.apps.c3smonkey.ch"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          url-expression: "uri"

#          url-expression: "'http://'+serviceId"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full
