spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/myhelsana/services/medicheck/**
          filters:
            - StripPrefix=3
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true
          uri: "http://medicheck-service-development.apps.c3smonkey.ch"

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true
  info:
    git:
      mode: full

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
          %clr([${spring.zipkin.service.name:${spring.application.name:-}},){magenta}%clr(%X{X-B3-TraceId:-},){yellow}%clr(%X{X-B3-SpanId:-},){cyan}%clr(,%X{X-Span-Export:-}]){blue}%clr([%8.15t]){cyan}
          %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m
          ){faint}%n"


#server:
##  port: 9090
##---
##spring:
##  cloud:
##    gateway:
##      default-filters:
##        - name: GlobalFilter
##      routes:
##        - id: nt-ms1
##          uri: http://localhost:9091/
##          predicates:
##            - Path=/nt-ms1/**
##          filters:
##            - name: PreFilter
##            - name: PostFilter
##        - id: nt-ms2
##          uri: http://localhost:9092/
##          predicates:
##            - Path=/nt-ms2/**