apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: gateway-pipeline
    name: gateway-pipeline
  name: gateway-ci-pipeline
spec:
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/marzelwidmer/spring-cloud-gateway.git
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile

